services:
  web:
    image: docker.io/library/nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
